### ISSUE TITLE
Rich Picture

### ISSUE THREAD

**Issue by micaellagouveia** [2020-1-Eulivro/Wiki#1]
## Descrição da Issue
Será realizada a criação dos *rich pictures* como método importante para a pré-rastreabilidade do projeto.

### Tasks: 
- [ ] Desenho do *RichPicture* (Pedro Igor).
- [x] Desenho do *RichPicture*(Eduardo Lima).
- [x] Desenho do *RichPicture*(Sofia Patrocínio).
- [ ] Desenho do *RichPicture*(Gabriel Alves).
- [x] Desenho do *RichPicture*(Lucas Fellipe).
- [x] Desenho do *RichPicture*(Gabriel Davi).
- [x] Desenho do *RichPicture*(Micaella Gouveia).
- [x] Desenho do *RichPicture*(Caio Fernandes).
- [x] Desenho do *RichPicture*(Guilherme).
- [ ] Desenho do *RichPicture*(Iuri Severo).
- [ ] Desenho do *RichPicture*(João Pedro).

### Critérios de aceitação
- [x] Estar documentado na Wiki.
- [x] Ter uma explicação sobre a técnica e o porquê do uso.

**Comment by guilherme-mendes** [comment]
Segue algumas referências interessantes para criação de Rich Pictures.
* HOWARD, Andrew Monk. Steve. The Rich Picture: A Tool for Reasoning About Work Context.
* Complexity and Rich Pictures. http://leadershipforchange.org.uk/wp-content/uploads/Complexity-and-rich-pictures.pdf.

**Comment by micaellagouveia** [comment]
Galera, coloquei uma task para cada um, assim que fizer seu rich picture e documentar, marca como feito.
