### ISSUE TITLE
Entrevista

### ISSUE THREAD

**Issue by sofiapatrocinio** [2020-1-Eulivro/Wiki#10]
## Descrição da Issue
Utilizar a técnica de elicitação de entrevista.

### Tasks: 
- [x] Definir perguntas.
- [x] Definir público-alvo.
- [ ] Coletar respostas.

### Critérios de aceitação
- [ ] Estar documentado na Wiki.
- [ ] Ter uma explicação sobre a técnica e o porquê do uso.
