### ISSUE TITLE
Criar Introspecção

### ISSUE THREAD

**Issue by ghost** [2020-1-Eulivro/Wiki#12]
## Descrição da Issue
Utilizar a técnica de Introspecção para a elicitação de requisitos.

### Tasks: 
- [x] Observar os conteúdos de seus próprios estados mentais.
- [x] Criar um documento reunindo dados adquiridos pela técnica.

### Critérios de aceitação
- [x] Estar documentado na Wiki.
- [x] Ter uma explicação sobre a técnica e o porquê do uso.
