### ISSUE TITLE
Criar Políticas de Repositório

### ISSUE THREAD

**Issue by ghost** [2020-1-Eulivro/Wiki#14]
## Descrição da Issue
Criar políticas de repositório para pessoas que queiram contribuir com o nosso projeto.
### Tasks: 
- [x] Criar template de Issue.
- [x] Criar template de pull request.
- [x] Criar template de commits.
- [x] Criar template de branches.

### Critérios de aceitação
- [x] Estar documentado na Wiki.
- [x] Que todos os membros do grupo estejam de acordo.
