### ISSUE TITLE
Criar Argumentação

### ISSUE THREAD

**Issue by micaellagouveia** [2020-1-Eulivro/Wiki#2]
## Descrição da Issue
Utilizar a técnica de pré-rastreabilidade da argumentação mantendo a rastreabilidade e conclusão do grupo documentando toda a etapa de escolha de tema.

### Tasks: 
- [ ] Ouvir gravações das reuniões.
- [ ] Criar gráficos das argumentações.

### Critérios de aceitação
- [ ] Estar documentado na Wiki.
- [ ] Ter uma explicação sobre a técnica e o porquê do uso.

**Comment by guilherme-mendes** [comment]
* JURETA, Ivan; MYLOPOULOS, John; FAULKNER, Stéphane. Analysis of Multi-Party Agreement in Requirements Validation, Proceedings of the 17th IEEE International Requirements Engineering Conference IEEE Computer Society, pp. 57-66, 2009.
