### ISSUE TITLE
Criar 5W2H

### ISSUE THREAD

**Issue by sofiapatrocinio** [2020-1-Eulivro/Wiki#4]
## Descrição da Issue
Utilizar a técnica de pré-rastreabilidade de 5W2H.

### Tasks: 
- [x] Definir What - O que faremos?
- [x] Definir Why - Por que fazer?
- [x] Definir Where - Onde faremos?
- [x] Definir Who - Quem faz?
- [x] Definir When - Quando fazer?
- [x] Definir How - Como fazer?
- [x] Definir How much- Quanto custa?

### Critérios de aceitação
- [x] Estar documentado na Wiki.
- [x] Ter uma explicação sobre a técnica e o porquê do uso.
