### ISSUE TITLE
Fazer Mapa Mental

### ISSUE THREAD

**Issue by sudjoao** [2020-1-Eulivro/Wiki#5]
## Descrição da Issue
Criar mapa mental para definir quais possíveis fluxos a ideia principal do aplicativo pode seguir.
### Tasks: 
- [ ] Criar mapa mental.
### Critérios de aceitação:
- [ ] Estar documentado na Wiki.
- [ ] Ter uma explicação sobre a técnica e o porquê do uso.

**Comment by sudjoao** [comment]
Hoje, reunido em pareamento com o @iurisevero, começamos a fazer a primeira versão do mapa mental, atualmente o mapa mental assim:

**Comment by sudjoao** [comment]
Hoje, reunido em pareamento com o @iurisevero, começamos a fazer a primeira versão do mapa mental, como se pode ver na imagem abaixo, atualmente o mapa está contando apenas com os textos, iremos tentar adicionar todas as imagens ainda hoje.

**Comment by sudjoao** [comment]
Hoje, reunido em pareamento com o @iurisevero, começamos a fazer a primeira versão do mapa mental, como se pode ver na imagem abaixo, atualmente o mapa está contando apenas com os textos, iremos tentar adicionar todas as imagens ainda hoje.

Imagem do mapa mental atual:

![mapa_mental](https://user-images.githubusercontent.com/46005310/76897200-0d7bd080-6872-11ea-96f3-98651a7ccdc0.png)

**Comment by sudjoao** [comment]
testando bot
