### ISSUE TITLE
Criar Brainstorming

### ISSUE THREAD

**Issue by micaellagouveia** [2020-1-Eulivro/Wiki#6]
## Descrição da Issue
Utilizar a técnica de brainstorming e documentá-la.

### Tasks: 
- [x] Ouvir gravações das reuniões.
- [x] Fazer o relato do que foi comentado no brainstorming.
- [x] Fazer mapa mental de cada assunto tratado.
- [x] Documentar brainstorming.
- [ ] Listar os requisitos levantados.

### Critérios de aceitação

- [x] Estar documentado na Wiki.
- [x] Ter uma explicação da técnica e o porquê do uso.
- [x] Tabela de versionamento.

**Comment by gitgabiru** [comment]
É necessário listar os requisitos levantados pela técnica
