### ISSUE TITLE
Criar Diagrama de Ishikawa

### ISSUE THREAD

**Issue by iurisevero** [2020-1-Eulivro/Wiki#7]
## Descrição da Issue
Criar um Diagrama de Ishikawa para descrever os problemas alcançados pelo projeto.
Exemplo de diagrama de Ishikawa:

![image](https://user-images.githubusercontent.com/42645264/76806014-0ba50500-67bf-11ea-89a6-87c6f3cb9c49.png)

### Tasks: 
- [x] Criar um Diagrama de Ishikawa.
- [x] Criar um documento reunindo dados adquiridos pela técnica.

### Critérios de aceitação
- [x] Estar documentado na Wiki.
- [x] Ter uma explicação sobre a técnica e o porquê do uso.
