### ISSUE TITLE
Criar Storyboard

### ISSUE THREAD

**Issue by guilherme-mendes** [2020-1-Eulivro/Wiki#8]
## Descrição da Issue
Usar a técnica de Storyboard para a elicitação de requisitos.

### Tasks: 
- [x] Criar um storyboard.
- [x] Criar um documento reunindo dados adquiridos pela técnica.

### Critérios de aceitação
- [x] Estar documentado na Wiki.
- [x] Ter uma explicação sobre a técnica e o porquê do uso.

**Comment by guilherme-mendes** [comment]
**StoryBoard v0.1**

![Captura de tela de 2020-03-16 21-13-44](https://user-images.githubusercontent.com/37874689/76809923-27aea380-67cb-11ea-8ed4-13cb877e325f.png)

**Comment by guilherme-mendes** [comment]
**StoryBoard v0.2**

![Captura de tela de 2020-03-17 11-33-27](https://user-images.githubusercontent.com/37874689/76866829-71d36b80-6843-11ea-9c6a-11223935ed40.png)

![storyboard-eulivro2-animated-gif](https://user-images.githubusercontent.com/37874689/76866902-8b74b300-6843-11ea-87ad-0e89036348bc.gif)

**Comment by GabrielDVpereira** [comment]
@guilherme-mendes  na hora de criar um storyBoard, tenta pensar em uma feature em específica do app e problematizar alguma situação que essa feature resolve. Ex: Alguém lendo recomendações da web acha ruim ter que pensquisar o livro em mercados pra achar a melhor opção, ai ele acha o EuLIvro e acha ótimo a disponibilidade de links para os melhores mercados para o livro

**Comment by GabrielDVpereira** [comment]
![EuLivro1](https://user-images.githubusercontent.com/37307099/76885179-98060500-685d-11ea-9e6b-ae9aeaed50a1.png)

**Comment by GabrielDVpereira** [comment]
![eulivro2](https://user-images.githubusercontent.com/37307099/76885220-a81de480-685d-11ea-9fda-36f7f2276adb.png)

**Comment by GabrielDVpereira** [comment]
![eulivro3](https://user-images.githubusercontent.com/37307099/76889402-4ad96180-6864-11ea-96b8-a7ce0e90e671.png)
