### ISSUE TITLE
Criar Questionário

### ISSUE THREAD

**Issue by ghost** [2020-1-Eulivro/Wiki#9]
## Descrição da Issue
Utilizar a técnica questionário para a elicitação de requisitos.

### Tasks: 
- [x] Criar um questionário.
- [ ] Criar um documento reunindo dados adquiridos pela técnica.

### Critérios de aceitação
- [ ] Estar documentado na Wiki.
- [ ] Ter uma explicação sobre a técnica e o porquê do uso.
